version: "3.8"

services:
  px4-sitl:
    image: px4-sitl
    container_name: px4-sitl
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/home/px4user/.Xauthority
      - PX4_GZ_WORLD=aruco
      - PX4_SIM_SPEED_FACTOR=1.0
      - HEADLESS=1
    network_mode: host
    privileged: true
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "$HOME/.Xauthority:/home/px4user/.Xauthority:rw"
    stdin_open: true
    tty: true
